version: '3'
services:
  lyric:
    build:
      context: ./lyric
      dockerfile: ./docker/Dockerfile
    ports:
    - "5000:5000"
    volumes:
    - ./lyric/src:/home/app/lyric/src
  voice:
    build:
      context: ./voice
      dockerfile: ./docker/Dockerfile
    ports:
    - "5001:5001"
    volumes:
    - ./voice/src:/home/app/voice/src
    - ./voice/wav:/home/app/voice/wav
